import { Freelancer, JobOpportunity, Referral } from './types';

export const mockFreelancers: Freelancer[] = [
  {
    id: '1',
    fid: 'fc_001',
    baseWallet: '0x1234...5678',
    name: 'Sarah Chen',
    skills: ['React', 'TypeScript', 'Next.js', 'UI/UX'],
    quality_score: 92,
    trust_badge: 'top10',
    successful_hires: 24,
    endorsements_count: 18,
    bio: 'Senior frontend developer with 5+ years building production apps',
    portfolio_url: 'https://sarahchen.dev',
    avatar: '👩‍💻',
    created_at: new Date('2023-01-15'),
  },
  {
    id: '2',
    fid: 'fc_002',
    baseWallet: '0x8765...4321',
    name: 'Marcus Johnson',
    skills: ['Solidity', 'Web3', 'Smart Contracts', 'DeFi'],
    quality_score: 88,
    trust_badge: 'verified',
    successful_hires: 15,
    endorsements_count: 12,
    bio: 'Blockchain engineer specializing in DeFi protocols',
    avatar: '👨‍💼',
    created_at: new Date('2023-03-20'),
  },
  {
    id: '3',
    fid: 'fc_003',
    baseWallet: '0xabcd...efgh',
    name: 'Elena Rodriguez',
    skills: ['Python', 'AI/ML', 'Data Science', 'APIs'],
    quality_score: 95,
    trust_badge: 'top10',
    successful_hires: 31,
    endorsements_count: 25,
    bio: 'AI engineer building intelligent systems',
    avatar: '👩‍🔬',
    created_at: new Date('2022-11-10'),
  },
];

export const mockJobs: JobOpportunity[] = [
  {
    id: 'job_1',
    poster_fid: 'poster_001',
    title: 'Senior React Developer for DeFi Dashboard',
    description: 'Need experienced React dev to build real-time trading dashboard with Web3 integration',
    required_skills: ['React', 'TypeScript', 'Web3', 'TailwindCSS'],
    bounty_amount: 350,
    escrow_contract_address: '0xescrow1',
    status: 'open',
    deadline: new Date('2024-02-15'),
    urgency_level: 'high',
    created_at: new Date('2024-01-10'),
  },
  {
    id: 'job_2',
    poster_fid: 'poster_002',
    title: 'Smart Contract Auditor',
    description: 'Looking for security expert to audit our NFT marketplace contracts',
    required_skills: ['Solidity', 'Security', 'Auditing', 'DeFi'],
    bounty_amount: 500,
    escrow_contract_address: '0xescrow2',
    status: 'open',
    deadline: new Date('2024-02-20'),
    urgency_level: 'medium',
    created_at: new Date('2024-01-12'),
  },
  {
    id: 'job_3',
    poster_fid: 'poster_003',
    title: 'AI Integration Specialist',
    description: 'Build AI-powered recommendation engine for our platform',
    required_skills: ['Python', 'AI/ML', 'APIs', 'Data Science'],
    bounty_amount: 275,
    escrow_contract_address: '0xescrow3',
    status: 'open',
    deadline: new Date('2024-02-25'),
    urgency_level: 'low',
    created_at: new Date('2024-01-14'),
  },
];

export const mockReferrals: Referral[] = [
  {
    id: 'ref_1',
    referrer_id: 'user_001',
    freelancer_id: '1',
    job_opportunity_id: 'job_1',
    match_score: 94,
    endorsement_text: 'Sarah is perfect for this - built 3 similar dashboards last year with excellent results',
    status: 'hired',
    bounty_status: 'released',
    payout_amount: 297.50,
    payout_tx_hash: '0xtx123',
    created_at: new Date('2024-01-11'),
    hired_at: new Date('2024-01-18'),
  },
  {
    id: 'ref_2',
    referrer_id: 'user_001',
    freelancer_id: '2',
    job_opportunity_id: 'job_2',
    match_score: 91,
    endorsement_text: 'Marcus has audited 10+ protocols with zero exploits. Highly recommend.',
    status: 'accepted',
    bounty_status: 'escrowed',
    created_at: new Date('2024-01-13'),
  },
];

export const mockUserStats = {
  total_earnings: 1247.50,
  successful_referrals: 8,
  conversion_rate: 75,
  pending_bounties: 850,
  active_referrals: 3,
};
